// src/config/executiveThemeLayouts.ts

export const executiveThemeLayouts = {
  title: {
    background: "background",
    shapes: [
      {
        type: "triangle",
        x: 7,
        y: 4.5,
        w: 2,
        h: 1.5,
        fill: "accent",
        line: { width: 1, dashType: "solid" },
      },
      {
        type: "rect",
        x: 7,
        y: -0.75,
        w: 3.65,
        h: 6.33,
        fill: "secondary",
        line: { width: 1, dashType: "solid" },
        rotate: -18,
      },
      {
        type: "rect",
        x: 8,
        y: -1,
        w: 3.65,
        h: 6.57,
        fill: "primary",
        line: { width: 1, dashType: "solid" },
        rotate: -20,
      },
    ],
    titleText: {
      source: "slide.title",
      x: 0.8,
      y: 2.2,
      w: 6.5,
      h: 2,
      fontSize: 32,
      fontWeight: "bold",
      color: "textDark",
      align: "left",
      fontType: "heading",
    },
    decorations: [
      {
        type: "roundRect",
        x: 0.8,
        y: 4.6,
        w: 4,
        h: 0.6,
        fill: "primary",
        line: { width: 1, dashType: "solid" },
        radius: 0.15,
      },
    ],
    subtitleText: {
      source: "slide.subtitle",
      fallback: "Presented by Your Company",
      x: 1,
      y: 4.6,
      w: 3.7,
      h: 0.6,
      fontSize: 16,
      color: "textLight",
      align: "left",
      fontType: "body",
    },
  },

  content: {
    background: "background",
    titleText: {
      source: "slide.title",
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.5,
      fontSize: 32,
      fontWeight: "bold",
      color: "primary",
      fontType: "heading",
      align: "left",
    },
    bullets: {
      startX: 1,
      startY: 1,
      spacingY: 0.6,
      fontSize: 18,
      color: "text",
      fontType: "body",
      w: 8,
      style: {
        type: "bullet",
        prefix: "• ",
      },
      itemDecoration: {
        enabled: true,
        shape: "roundRect", // "rect" | "roundRect" | "circle" | "diamond"
        fill: "surface", // Background color
        padding: 0.15, // Space inside shape
        offsetX: -0.3, // Offset from text start
        offsetY: 0, // Offset from text top
        width: 8.3, // Shape width
        height: 0.5, // Shape height
        line: {
          width: 0, // 0 = no border
          color: "primary",
        },
        zIndex: "back", // "back" | "front" (render before or after text)
      },
    },
  },

  twoColumn: {
    background: "background",
    titleText: {
      source: "slide.title",
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.5,
      fontSize: 30,
      fontWeight: "bold",
      color: "primary",
      fontType: "heading",
      align: "left",
    },
    leftColumn: {
      startX: 0.7,
      startY: 1.2,
      spacingY: 0.6,
      fontSize: 18,
      color: "text",
      fontType: "body",
      w: 4,
      style: {
        type: "bullet",
        prefix: "• ",
      },
      itemDecoration: {
        enabled: true,
        shape: "rect",
        fill: "surface",
        padding: 0.1,
        offsetX: -0.25,
        offsetY: -0.05,
        width: 4.2,
        height: 0.5,
        line: {
          width: 0,
        },
        zIndex: "back",
      },
    },
    rightColumn: {
      startX: 5.5,
      startY: 1.2,
      spacingY: 0.6,
      fontSize: 18,
      color: "text",
      fontType: "body",
      w: 4,
      style: {
        type: "bullet",
        prefix: "• ",
      },
      itemDecoration: {
        enabled: true,
        shape: "rect",
        fill: "surface",
        padding: 0.1,
        offsetX: -0.25,
        offsetY: -0.05,
        width: 4.2,
        height: 0.5,
        line: {
          width: 0,
        },
        zIndex: "back",
      },
    },
  },

  plan: {
    background: "background",
    shapes: [
      {
        type: "rect",
        x: 7,
        y: 2,
        w: 3.65,
        h: 2,
        fill: "secondary",
        line: { width: 1, dashType: "solid" },
      },
      {
        type: "rect",
        x: 8,
        y: -1,
        w: 3.65,
        h: 6.57,
        fill: "primary",
        line: { width: 1, dashType: "solid" },
        rotate: -20,
      },
    ],
    titleText: {
      source: "slide.title",
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.5,
      fontSize: 30,
      fontWeight: "bold",
      color: "primary",
      fontType: "heading",
      align: "left",
    },
    plan: {
      source: "slide.content",
      startX: 1,
      startY: 1.2,
      spacingY: 0.8,
      fontSize: 18,
      color: "text",
      fontType: "body",
      w: 6,
      style: {
        type: "numbered",
        format: "${number} ${text}",
        numberFormat: "1)",
      },
      itemDecoration: {
        enabled: true,
        shape: "roundRect",
        fill: "surface",
        padding: 0.2,
        offsetX: -0.4,
        offsetY: -0.1,
        width: 6.4,
        height: 0.65,
        radius: 0.1,
        line: {
          width: 2,
          color: "primary",
        },
        zIndex: "back",
      },
    },
  },

  stats: {
    background: "surface",
    titleText: {
      source: "slide.title",
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.5,
      fontSize: 30,
      fontWeight: "bold",
      color: "primary",
      fontType: "heading",
      align: "left",
    },
    grid: {
      columns: 3,
      baseX: 0.5,
      baseY: 1.5,
      cellW: 3,
      cellH: 1.8,
      spacingX: 3,
      spacingY: 2,
      fontSize: 16,
      color: "textDark",
      fontType: "body",
      shape: "roundRect",
      shapeFill: "background",
      textFormat: "${label}\n${value}\n${description}",
    },
  },
};
